spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/depository?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: pjy
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    property-naming-strategy: SNAKE_CASE #下划线转驼峰
    default-property-inclusion: non_null #过滤null值

server:
  port:  8080

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  type-aliases-package: com.pjy.simplewarehouse.domain.entity
  configuration:
    map-underscore-to-camel-case: true
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    #com.pjy.simplewarehouse.dao: debug  #第2种sql打印配置
